# Étape 1 : utiliser Node.js
FROM node:18

# Étape 2 : définir le dossier de travail
WORKDIR /app

# Étape 3 : copier package.json et installer les dépendances
COPY package*.json ./
RUN npm install

# Étape 4 : copier le reste du frontend
COPY . .

# Étape 5 : exposer le port Vite
EXPOSE 5173

# Étape 6 : démarrer en mode dev
CMD ["npm", "run", "dev", "--", "--host"]
