version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: atelier-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: atelier-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: atelier-frontend
    restart: always
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongo_data:
